### ISSUE TITLE
Maintenance Mode always detected

### ISSUE THREAD

**Issue by leadcoin** [SpecDevelopment/SPECTRA#1]
```
root@chainexplorer:/var/www/html/utility# php maint_crontab.php
10/19/2015 14:44:37 - 0: Beginning maintenance.
10/19/2015 14:44:37 - 1: Maintenance mode detected, exiting.
```

Before, following instructions, I created an entry in crontab that included running this php script but nothing seemed to be happening. I removed it from crontab and have tried running it manually for testing but this is all that's happening, even after restarting.

It's worked to an extent but has frozen on 12488 block:

http://chainexplorer.info/

I tried removing it as an incomplete block but maint_crontab won't let me resume giving me the same error. Thoughts?

**Comment by SpecDevelopment** [comment]
Ive messaged Jake, hopefully what I just selected will also send him an alert or similar on github itself.

Ive been checking on your block explorer and I think Jake can explain the system, possible solutions etc better than anyone at the moment.

**Comment by CallMeJake** [comment]
Hello,

**Comment by CallMeJake** [comment]
If maintenance or loading was interrupted and the flags are still set, you can use the script "maint_resetflag.php" found in the utility directory to take it out of that maintenance mode.

The flags are necessary to ensure that two copies of the scripts don't start loading duplicate blocks.

**Comment by leadcoin** [comment]
I should've rtfm'd a little better, since I should've known that script did SOMETHING. My bad.

Looking like that'll fix it since it's working now. Once maint_crontab catches up with the blockchain count does it terminate (and thus why making a cronjob that runs every minute is necessary) or run indefinitely? Because I have it running in screen right now as a cheat and will just leave it like that if it'll work, but still have days to go before I have to worry about it (currently 20k blocks in, 880k to go)

**Comment by CallMeJake** [comment]
Yes, when maint_crontab reaches the block height it found in the node when it was first executed, it will self terminate. That's also the reason for the maintenance mode flag.  If it takes several minutes to catch up with the node, we don't want another instance starting due to a shorter crontab timer and then both instances trying to load the same blocks.

I'm not sure the target block time for fedoracoin but you can set the crontab timer to approximately that, if it's more than a minute, and it would probably be fine.

 If the VPS has low resources you could disable the crontab until the database is basically caught up, and it would let things proceed a little faster.  It only takes a moment to check the flags though, so it's probably not a big deal either way.
